<?xml version="1.0" encoding="utf-8"?>
<Database Name="aux2" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Channel" Member="Channels">
    <Type Name="Channel">
      <Column Name="Id" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Points" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Rank" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Bio" Type="System.String" DbType="NVarChar(2048)" CanBeNull="true" />
      <Column Name="Avatar" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Forum" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Suggestion" Member="SuggestionTables">
    <Type Name="SuggestionTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(24) NOT NULL" CanBeNull="false" />
      <Column Name="Suggestion" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.PrivateMessages" Member="PrivateMessageInfos">
    <Type Name="PrivateMessageInfo">
      <Column Name="pmid" Member="PmID" Storage="_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fromid" Member="FromID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="toid" Member="ToID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="subject" Member="Subject" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="message" Member="Message" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="timesent" Member="TimeSent" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="timeread" Member="TimeRead" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>